import type { EntityRef } from './entity.ts';

/**
 * Generate an `entities.d.ts` that augments `KnownEntities`, so entity refs
 * autocomplete and typos fail typechecking.
 */
export function generateEntityTypes(refs: readonly (EntityRef | string)[]): string {
  const unique = [...new Set(refs)].toSorted();
  const lines = unique.map((ref) => `    ${JSON.stringify(ref)}: true;`);
  return [
    '// Generated by @hash/core. Do not edit.',
    "import '@hash/core';",
    '',
    "declare module '@hash/core' {",
    '  interface KnownEntities {',
    ...lines,
    '  }',
    '}',
    '',
  ].join('\n');
}
