import { existsSync, lstatSync, mkdirSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { DiscoveredDashboard } from './discovery.ts';

/** Absolute path of the runtime's own `app/` directory (root layout, home, route helpers). */
export const RUNTIME_APP_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'app');

export const HASH_DIR = '.hash';

const q = (value: string) => JSON.stringify(value);
const app = (file: string) => q(join(RUNTIME_APP_DIR, file));

/**
 * Writes the React Router app that ties the runtime to an instance's
 * dashboards: `<root>/.hash/`. Generated modules only re-export from absolute
 * paths (runtime app + dashboard sources), so nothing here depends on how
 * packages happen to be laid out in `node_modules`.
 */
export function generateApp(root: string, dashboards: DiscoveredDashboard[]): string {
  const hashDir = join(root, HASH_DIR);
  const appDir = join(hashDir, 'app');
  const routesDir = join(appDir, 'routes');
  rmSync(appDir, { recursive: true, force: true });
  mkdirSync(routesDir, { recursive: true });

  const write = (file: string, content: string) => writeFileSync(join(hashDir, file), content);

  write(
    'react-router.config.ts',
    `// Generated by hash. Do not edit.
export default { appDirectory: 'app', buildDirectory: 'build', ssr: false };
`,
  );

  linkRuntimeDeps(hashDir);

  write(
    'app/entry.client.tsx',
    `// Generated by hash. Do not edit.
import ${app('entry.client.tsx')};
`,
  );
  write(
    'app/entry.server.tsx',
    `// Generated by hash. Do not edit.
export { default } from ${app('entry.server.tsx')};
`,
  );

  write(
    'vite.config.ts',
    `// Generated by hash. Do not edit.
export { default } from ${q(join(RUNTIME_APP_DIR, '..', 'src', 'vite-config.ts'))};
`,
  );

  write(
    'app/root.tsx',
    `// Generated by hash. Do not edit.
export { default, Layout, HydrateFallback } from ${app('root.tsx')};
`,
  );

  const imports = dashboards
    .map((d, i) => `import manifest${i} from ${q(d.manifestFile)};`)
    .join('\n');
  write(
    'app/routes/home.ts',
    `// Generated by hash. Do not edit.
import { createHome } from ${app('home.tsx')};
${imports}

export const meta = () => [{ title: 'Dashboards' }];
export default createHome([${dashboards.map((_, i) => `manifest${i}`).join(', ')}]);
`,
  );

  for (const d of dashboards) {
    write(
      `app/routes/dashboard.${d.id}.ts`,
      `// Generated by hash. Do not edit.
import { createDashboardRoute, dashboardMeta } from ${app('dashboard-route.tsx')};
import manifest from ${q(d.manifestFile)};
import routes from ${q(d.routesFile)};

export const meta = dashboardMeta(manifest);
export default createDashboardRoute(manifest, routes);
`,
    );
  }

  const entries = [
    `{ index: true, file: 'routes/home.ts' }`,
    ...dashboards.map(
      (d) =>
        `{ id: ${q(`dashboard-${d.id}`)}, path: ${q(`dashboard/${d.id}/*`)}, file: ${q(`routes/dashboard.${d.id}.ts`)} }`,
    ),
  ];
  write(
    'app/routes.ts',
    `// Generated by hash. Do not edit.
export default [
  ${entries.join(',\n  ')},
];
`,
  );

  return hashDir;
}

/** Packages that must resolve to a single copy from `.hash/`, whatever the instance's node_modules layout. */
const SHARED_DEPS = ['react', 'react-dom', 'react-router', '@hash/core', '@hash/ui'];

function linkRuntimeDeps(hashDir: string) {
  const require = createRequire(join(RUNTIME_APP_DIR, '..', 'package.json'));
  for (const name of SHARED_DEPS) {
    const packageJson = require.resolve(`${name}/package.json`);
    const target = dirname(packageJson);
    const link = join(hashDir, 'node_modules', name);
    mkdirSync(dirname(link), { recursive: true });
    if (existsSync(link) || isSymlink(link)) rmSync(link, { recursive: true, force: true });
    symlinkSync(target, link, 'dir');
  }
}

const isSymlink = (path: string) => {
  try {
    return lstatSync(path).isSymbolicLink();
  } catch {
    return false;
  }
};
