/**
 * Generates `packages/ui/src/icon-data.ts`: every icon from two packs, combined — Lucide (`lu:`)
 * and Tabler's outline set (`tb:`), addressed as `<pack>:<name>` (matching Home Assistant's own
 * `mdi:`-prefixed icon convention). Run via `pnpm generate:icons`. CI fails if the output would
 * change.
 *
 * Deliberately not curated: a dashboard author can use any `lu:`/`tb:` icon name either pack
 * actually ships, with no entry to add here and no script to run — this file only needs
 * regenerating when the pack *versions* in `package.json` change. Pick the best-looking pack per
 * icon case by case (e.g. `lu:lightbulb` but `tb:vacuum-cleaner`); there's no requirement to stay
 * within one pack.
 *
 * Both source packages ship each icon as a small array of SVG child nodes (`[tag, attrs][]`) —
 * Lucide as one real ES module per icon (so this just imports them directly), Tabler as one
 * combined JSON file covering its whole outline set.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { formatWithRepoConfig } from './format.ts';

const OUT_FILE = join(import.meta.dirname, '..', 'packages', 'ui', 'src', 'icon-data.ts');

const LUCIDE_ICONS_DIR = join(
  import.meta.dirname,
  '..',
  'node_modules',
  'lucide',
  'dist',
  'esm',
  'icons',
);

const TABLER_OUTLINE_FILE = join(
  import.meta.dirname,
  '..',
  'node_modules',
  '@tabler',
  'icons',
  'tabler-nodes-outline.json',
);

type IconNode = readonly [tag: string, attrs: Record<string, string>];

async function loadAllLucide(): Promise<[string, readonly IconNode[]][]> {
  const files = readdirSync(LUCIDE_ICONS_DIR).filter((f) => f.endsWith('.mjs'));
  const entries: [string, readonly IconNode[]][] = [];
  for (const file of files) {
    const name = file.slice(0, -'.mjs'.length);
    const fileUrl = pathToFileURL(join(LUCIDE_ICONS_DIR, file)).href;
    const mod = (await import(fileUrl)) as { default: readonly IconNode[] };
    entries.push([`lu:${name}`, mod.default]);
  }

  return entries;
}

function loadAllTabler(): [string, readonly IconNode[]][] {
  const data = JSON.parse(readFileSync(TABLER_OUTLINE_FILE, 'utf8')) as Record<
    string,
    readonly IconNode[]
  >;

  return Object.entries(data).map(([name, nodes]) => [`tb:${name}`, nodes]);
}

const entries = [...(await loadAllLucide()), ...loadAllTabler()].toSorted(([a], [b]) =>
  a.localeCompare(b),
);

const raw = `// Generated by \`pnpm generate:icons\` from \`scripts/generate-icons.ts\`. Do not edit by
// hand — it only needs rerunning when the \`lucide\`/\`@tabler/icons\` versions in the root
// package.json change. Every icon either pack ships is already here; there's nothing to add.

/** An SVG child element: its tag name and attributes, e.g. \`['path', { d: '...' }]\`. */
export type IconNode = readonly [tag: string, attrs: Record<string, string>];

// A plain \`Record<string, ...>\`, not \`keyof typeof ICON_NODES\` — with ~${entries.length} entries,
// deriving \`IconName\` as a literal union of every key makes the type checker (and editor
// autocomplete) grind to a halt. \`IconName\` below is a cheap template-literal type instead: it
// checks the pack prefix, not every exact name: a real but mistyped icon id (\`lu:lihgtbulb\`)
// still typechecks, so \`Icon\` also checks at runtime and warns once if the name isn't found.
export const ICON_NODES: Record<string, readonly IconNode[]> = {
${entries.map(([id, nodes]) => `  ${JSON.stringify(id)}: ${JSON.stringify(nodes)},`).join('\n')}
};

/** An icon id, e.g. \`'lu:lightbulb'\`, \`'tb:vacuum-cleaner'\` — see \`ICON_NODES\` for how exact-name
 * checking is traded for compiler speed here. */
export type IconName = \`lu:${'$'}{string}\` | \`tb:${'$'}{string}\`;
`;

const formatted = await formatWithRepoConfig(OUT_FILE, raw);

writeFileSync(OUT_FILE, formatted);
console.log(`Wrote ${OUT_FILE} (${entries.length} icons)`);
